services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: my-mysql-container
      DB_USER: support_user
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - my-network
networks:
  my-network:
    external: true 