services:
  test-mysql:
    image: mysql:9.3.0 
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./support-api/integration/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./support-api/integration/testdata.sql:/docker-entrypoint-initdb.d/testdata.sql
